import './globals.css'
import Nav from "./auth/Nav"
import QueryWrapper from "./auth/QueryWrapper"
import { ReactNode } from 'react'

export const metadata = {
  title: 'vondev fitness',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
} : {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className='mx-4 md:mx-48 xl:mx-96 bg-gray-200'>
        <QueryWrapper>
          {/* @ts-expect-error Server Component*/}
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  )
}