import './globals.css'
import Nav from "./auth/Nav"

export const metadata = {
  title: 'vondev fitness',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='mx-4 md:mx-48 xl:mx-96 bg-gray-200'>
        {/* @ts-expect-error Server Component */}
        <Nav />
        {children}
      </body>
    </html>
  )
}
